name: Update external dependencies

on:
  workflow_dispatch: {}
  schedule:
  - cron: '23 9 * * 6' # Every Saturday

concurrency:
  group: ${{ github.workflow }}:${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true
    - run: |
        sudo wget -O /usr/local/bin/semver \
          https://raw.githubusercontent.com/bats-core/bats-core/v1.11.0/contrib/semver
        sudo chmod a+x /usr/local/bin/semver
    - run: bash .github/workflows/dependencies.sh
      env:
        GIT_AUTHOR_NAME: Rancher Desktop WSL Distro Depdency Updater
        GIT_AUTHOR_EMAIL: donotuse@rancherdesktop.io # See rddepman
        GH_TOKEN: ${{ github.token }}
